name: Setup Python
description: Checkout repo & uv cache

inputs:
  enable-cache:
    description: "Enable caching for Python setup"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
        enable-cache: ${{ inputs.enable-cache }}